remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
logo: https://avatars.githubusercontent.com/yoshikawaa
github:
  public: true
  is_project_page: true
  repository_url: https://github.com/yoshikawaa/git-test
